@url = http://localhost:5000

### USERS ###

###
# @name auth
POST {{url}}/users/auth
Content-Type: application/json

{
    "email": "test@test.com"
}

###
# @name sign_in
@accessCode = {{auth.response.body.$.code}}

POST {{url}}/users/sing-in
Content-Type: application/json

{
    "email": "test@test.com",
    "accessCode": "{{accessCode}}"
}
###
@accessToken = {{sign_in.response.body.$.accessToken}}

GET {{url}}/users/me
Authorization: Bearer {{accessToken}}
###
GET {{url}}/users/recommendations
Authorization: Bearer {{accessToken}}
###
GET {{url}}/users/00000000-0000-0000-0000-000000000001
Authorization: Bearer {{accessToken}}
###
POST {{url}}/users
Content-Type: application/json

{
    "phone": "12345629",
    "email": "test5554@test.com",
    "name": "Maciej",
    "dateOfBirth": "1987-03-10",
    "sex": 1,
    "discoverSex": 2,
    "job": "McDonald's",
    "bio": ""
}
###
PATCH {{url}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "dateOfBirth": "1987-03-10",
    "discoverSex": 2,
    "discoverRange": 40,
    "discoverAgeFrom": 18,
    "discoverAgeTo": 45,
    "lat": 54.3719424,
    "lon": 18.6143541
}
###
DELETE {{url}}/users/00000000-0000-0000-0000-000000000001
Authorization: Bearer {{accessToken}}

### PHOTOS ###

GET {{url}}/photos/00000000-0000-0000-0000-000000000001
Authorization: Bearer {{accessToken}}
###
POST {{url}}/photos
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "userId": "00000000-0000-0000-0000-000000000001",
    "base64Bytes": "4pyTIMOgIGxhIG1vZGU="
}
###
PATCH {{url}}/photos
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "photoId": "00000000-0000-0000-0000-000000000001",
    "newOridinal": 0
}
###
DELETE {{url}}/photos/00000000-0000-0000-0000-000000000001
Authorization: Bearer {{accessToken}}

### MATCHES ###

###
GET {{url}}/matches
Authorization: Bearer {{accessToken}}
###
GET {{url}}/matches/00000000-0000-0000-0000-000000000001/messages
Authorization: Bearer {{accessToken}}
###
GET {{url}}/matches/00000000-0000-0000-0000-000000000001/messages/00000000-0000-0000-0000-000000000001
Authorization: Bearer {{accessToken}}
###
POST {{url}}/matches/00000000-0000-0000-0000-000000000001/messages
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "sendFromId": "00000000-0000-0000-0000-000000000001",
    "text": "hejka2"
}
###
PATCH {{url}}/matches/00000000-0000-0000-0000-000000000001/messages
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "messageId": "00000000-0000-0000-0000-000000000001"
}
###
DELETE {{url}}/matches/00000000-0000-0000-0000-000000000001
Authorization: Bearer {{accessToken}}

### SWIPES ###

GET {{url}}/like/00000000-0000-0000-0000-000000000002
Authorization: Bearer {{accessToken}}
###
GET {{url}}/pass/00000000-0000-0000-0000-000000000003
Authorization: Bearer {{accessToken}}
###