version: '3'

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: datingapp-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  datingApp-Api:
    image: datingapp-api
    container_name: datingApp-Api
    ports:
      - 5000:5000
      - 8443:8443
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_HTTP_PORT=5000
      - ASPNETCORE_HTTPS_PORT=8443
      - Storage__StoragePath=/app/storage

volumes:
  postgres:
    driver: local